export const Actiontypes = {
  SET_PRODUCT: "SET_PRODUCT",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE FROM CART",
  FLAG_COUNTER: "FLAG_COUNTER",
  INCREASE_COUNT: "INCREASE_COUNT",
  DECREASE_COUNT: "DECREASE_COUNT",
};
